import React from "react";
import Head from "next/head";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.css";

//This is a function that displays my web apps
export default function Index() {
  return (
    <div>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div>
        <h2>Hi, my name is Delaine. Welcome to my portfolio.</h2>

        <div className="grid">
          <div className="index-card">
            <h3>Web Apps</h3>
            <p>
              These are projects that I have worked on. They are built using a
              combination of the following technologies:
            </p>
            <ul>
              <li id="project">MongoDB</li>
              <li>MongoDB</li>
              <li>Express</li>
              <li>React</li>
              <li>Next.js</li>
              <li>NodeJS</li>
            </ul>{" "}
            <div className="container">
              <Link href="/webProjects">
                <a>
                  <button>
                    Go to <br /> Web Apps
                  </button>
                </a>
              </Link>
            </div>
          </div>
          <div className="index-card">
            <h3>Certificates</h3>
            <p>
              These are the certificates I have attained thus far. They concern
              the following technologies:
            </p>
            <ul>
              <li>C#</li>
              <li>Javascript</li>
              <li>AWS</li>
              <li>Java</li>
              <li>Kubernetes</li>
              <li>MongoDB</li>
            </ul>
            <div className="container">
              <Link href="/certificates">
                <a>
                  {" "}
                  <button>Go to Certificates</button>
                </a>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
