import React from "react";
import Head from "next/head";
import Link from "next/link";

//This is a function that displays my web apps
export default function WebProjects() {
  return (
    <div className="center">
      <Head>
        <title>Web Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <div>
        <p className="blurb">
          Hi, my name is Delaine. Welcome to my portfolio. If you click on the
          &#34;Go to Web App&#34; link of each project you will be directed to a
          working version of it. It will most likely be hosted on Vercel. All
          images used are either in the public domain or require attribution. If
          attribution is required it will be visible in the page in which the
          image is used. The Next.js apps are created with the help of an
          official Next.js example titled:{" "}
          <a
            rel="noreferrer"
            target="_blank"
            href="https://github.com/vercel/next.js/tree/canary/examples/with-mongodb-mongoose"
          >
            {" "}
            MongoDB and Mongoose With Next.js
          </a>
          . All projects are currently a work in progress.
        </p>
        <ul className="grid">
          <li className="project-list">
            <h2 className="project-name">Story Book </h2>
            <div id="project-links">
              <p>
                This app allows you to create and save characters and plots, as
                well as perform writing excercises through helpful prompts.
              </p>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://day-dream.vercel.app/"
                >
                  {" "}
                  <button>
                    {" "}
                    Go to <br />
                    Web App{" "}
                  </button>
                </a>{" "}
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/dayDream"
                >
                  {" "}
                  <button>
                    {" "}
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name"> Memory Game </h2>
            <div id="project-links">
              <p>
                Click on the button below to find out more about the
                application, its functions, and any attribution associated with
                it.
              </p>
              <Link href="webProjects\memoryGame">
                <button>Find out more</button>
              </Link>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://a-memory-game-seven.vercel.app/"
                >
                  {" "}
                  <button>
                    {" "}
                    Go to <br />
                    Web App{" "}
                  </button>
                </a>{" "}
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/A_Memory_Game"
                >
                  {" "}
                  <button>
                    {" "}
                    Go to
                    <br /> Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Pantry</h2>
            <div id="project-links">
              <p>
                Click on the button below to find out more about the
                application, its functions, and any attribution associated with
                it.
              </p>
              <Link href="webProjects\pantry">
                <button>Find out more</button>
              </Link>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://pantry-dusky.vercel.app/"
                >
                  <button>
                    Go to
                    <br /> Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/Pantry"
                >
                  <button>
                    Go to
                    <br /> Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">My Portfolio</h2>
            <div id="project-links">
              <p>
                This is the site that you are currently on.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">React</li>
                    <li id="project">Next.js</li>
                  </ul>{" "}
                </p>
              </p>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/delaine-abner-portfolio"
                >
                  {" "}
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Text Formatter</h2>
            <div id="project-links">
              <p>
                This site was created for people who are trying to clean data.
                It allows the user to remove characters, separate words by
                character, enclose strings in characters, and remove duplicates.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">React</li>
                  </ul>
                </p>
              </p>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://text-formatter-zeta.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to
                    <br /> Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/Text_Formatter"
                >
                  <button>
                    Go to
                    <br /> Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Calculator </h2>
            <div id="project-links">
              <p>
                This app allows you to add, subtract, multiply, and divide
                numbers. It has an interactive and colorful UI.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">Express</li>
                    <li id="project">React</li>
                    <li id="project">Redux</li>
                    <li id="project">Next.js</li>
                  </ul>{" "}
                </p>
              </p>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://calculator-mu-ten.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/calculator"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Drum Machine </h2>
            <div id="project-links">
              <p>
                This app allows you to play drum sounds using an interactive UI.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">React</li>
                    <li id="project">Redux</li>
                  </ul>{" "}
                </p>
              </p>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://drum-machine-app-ten.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App{" "}
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/Drum-Machine-App"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Markdown Preview </h2>
            <div id="project-links">
              <p>
                This app allows you to type text and view it as a formatted
                preview.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">React</li>
                  </ul>{" "}
                </p>
              </p>

              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://codepen.io/Delaine/pen/oNWOPyd"
                >
                  <button>
                    Go to <br />
                    Codepen
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Whack a Mole Game </h2>

            <div id="project-links">
              <p>
                Click on the button below to find out more about the
                application, its functions, and any attribution associated with
                it.
              </p>
              <Link href="/webProjects\wackAMole">
                <button>Find out more</button>
              </Link>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://whack-a-mole-green.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App{" "}
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/whack_a_mole"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Random Quote Generator </h2>
            <div id="project-links">
              <p>
                This app allows you to generate random quotes and change the
                application background.
                <p>
                  <h3 className="technologies">Technologies used:</h3>
                  <ul>
                    <li id="project">React</li>
                    <li id="project">NodeJS</li>
                  </ul>{" "}
                </p>
              </p>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://random-quote-generator-nu.vercel.app/"
                >
                  <button>
                    Go to <br />
                    Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/Random-Quote-Generator"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Connect 4 Game </h2>
            <div id="project-links">
              <p>
                Click on the button below to find out more about the
                application, its functions, and any attribution associated with
                it.
              </p>
              <Link href="/webProjects\connectFour">
                <button>Find out more</button>
              </Link>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://connect-four-game.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App{" "}
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/Connect_Four_Game"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>

          <li className="project-list">
            <h2 className="project-name">Snake Game </h2>
            <div id="project-links">
              <p>
                Click on the button below to find out more about the
                application, its functions, and any attribution associated with
                it.
              </p>
              <Link href="/webProjects\snakeGame">
                <button>Find out more</button>
              </Link>
              <h3 className="technologies">Technologies used:</h3>
              <ul>
                <li id="project">MongoDB</li>
                <li id="project">Express</li>
                <li id="project">React</li>
                <li id="project">NodeJS</li>
                <li id="project">Next.js</li>
              </ul>{" "}
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://snake-game-five-dun.vercel.app/newPlayer"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/snake_game"
                >
                  <button>
                    Go to <br />
                    Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Timer App </h2>
            <div id="project-links">
              <div>
                <p>
                  This app is similar to a pomodoro timer. Users can set a
                  countdown, as well as schedule breaks.
                  <p>
                    <h3 className="technologies">Technologies used:</h3>
                    <ul>
                      <li id="project">React</li>
                    </ul>{" "}
                  </p>
                </p>
              </div>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://timer-project-one.vercel.app/"
                >
                  <button>
                    {" "}
                    Go to <br />
                    Web App
                  </button>
                </a>
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://github.com/delaine3/timer-project"
                >
                  <button>
                    Go to
                    <br /> Source Code
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name">Simple Website</h2>
            <div id="project-links">
              <div>
                <p>
                  This is a website. All information in the paragraphs was
                  copied verbatim from{" "}
                  <a
                    rel="noreferrer"
                    target="_blank"
                    href="https://time.com/collection/guclassNamee-to-happiness/4791285/bond-with-people/"
                  >
                    this website
                  </a>
                  .
                  <p>
                    <h3 className="technologies">Technologies used:</h3>
                    <ul>
                      <li id="project">HTML</li>
                      <li id="project">CSS</li>
                    </ul>{" "}
                  </p>
                </p>
              </div>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://codepen.io/Delaine/pen/NWdZmyW"
                >
                  <button>
                    {" "}
                    Go to
                    <br /> Codepen
                  </button>
                </a>
              </div>
            </div>
          </li>
          <li className="project-list">
            <h2 className="project-name"> Survey Form Website</h2>
            <div id="project-links">
              <div>
                <p>
                  This is a survey form website.
                  <p>
                    <h3 className="technologies">Technologies used:</h3>
                    <ul>
                      <li id="project">HTML</li>
                      <li id="project">CSS</li>
                    </ul>{" "}
                  </p>
                </p>
              </div>
              <div className="container">
                <a
                  rel="noreferrer"
                  target="_blank"
                  href="https://codepen.io/Delaine/pen/oNBroGY"
                >
                  <button>
                    {" "}
                    Go to
                    <br /> Codepen
                  </button>
                </a>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  );
}
